/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.domain.jsonc --include-runtime=false` (hash: e0a6e138d77fd81bfe7a7b6b02a978e7)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/asset-edge");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
